apiVersion: v1
kind: Service
metadata:
  name: binary-calculator-service
spec:
  selector:
    app: binary-calculator
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8080
  type: LoadBalancer
